/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import helpers.StaticHelpers;
import javax.swing.JOptionPane;

/**
 *
 * @author jf_me
 */
public class UnitDlg extends javax.swing.JDialog {
    private StaticHelpers stat;
    /**
     * Creates new form UnitDlg
     */
    public UnitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setStat(StaticHelpers stat) {
        this.stat = stat;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitgrp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Okbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        csopt = new javax.swing.JRadioButton();
        usopt = new javax.swing.JRadioButton();
        euopt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Okbtn.setText("OK");
        Okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Okbtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 40));

        unitgrp.add(csopt);
        csopt.setText("Córdobas (C$)");
        jPanel2.add(csopt);

        unitgrp.add(usopt);
        usopt.setText("Dólares (U$)");
        jPanel2.add(usopt);

        unitgrp.add(euopt);
        euopt.setText("Euros (€)");
        jPanel2.add(euopt);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 159));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbtnActionPerformed
        if(unitgrp.isSelected(csopt.getModel())){
            stat.setUNIT("C$");
        }else if(unitgrp.isSelected(usopt.getModel())){
            stat.setUNIT("U$");
        }else if(unitgrp.isSelected(euopt.getModel())){
            stat.setUNIT("€");
        }else{
            JOptionPane.showMessageDialog(this, "NO VALID OPTION EXCEPTION", "", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_OkbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(stat.getUNIT()=="U$"){
            unitgrp.setSelected(usopt.getModel(), true);
        }else if(stat.getUNIT()=="€"){
            unitgrp.setSelected(euopt.getModel(), true);
        }else{
            unitgrp.setSelected(csopt.getModel(), true);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnitDlg dialog = new UnitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Okbtn;
    private javax.swing.JRadioButton csopt;
    private javax.swing.JRadioButton euopt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup unitgrp;
    private javax.swing.JRadioButton usopt;
    // End of variables declaration//GEN-END:variables
}
